---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

#name: my-bootc-os
# description will be included in the image's metadata
#description: This is my personal OS image.

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        
  - type: bling
    install:
        - rpmfusion

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.visualstudio.code
          - org.localsend.localsend_app
          - org.onlyoffice.desktopeditors
          - io.github.vikdevelop.SaveDesktop
          - dev.vencord.Vesktop
          - com.visualstudio.code
          - org.freedesktop.Platform.ffmpeg-full//24.08
      - scope: user # Also add Flathub user repo, but no user packages

  - type: dnf
    repos:
      #files:
      #  remove:
      #    - negativo17
      copr:
        - atim/starship

    install:
      packages:
        - micro
        - starship
        - alacritty
        - distrobox
        - git


    group-install:
      with-optional: true
      packages:
      - virtualization

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: brew
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
